
services:
  api:
    container_name: 'operations-api'
    build:
      context: .
    ports:
      - 8082:8080
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - ingsis-network


  db:
    container_name: 'postgres_db_ingsis'
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - operations:/var/lib/postgresql/data
    networks:
      - ingsis-network

volumes:
  operations:

networks:
  ingsis-network:
    external: true

