name: "Continuous Deployment"
on:
  push:
    branches:
      - dev
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tricolor-austral
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
           ghcr.io/tricolor-austral/echo:${{ steps.short-sha.outputs.sha }}

      - name: Refresh container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "ingsis-dev"
          key: ${{ secrets.INGSIS_DEV_KEY }}
          script: |
            cd operations-api
            docker-compose -f docker-compose.dev.yml stop operations-api
            docker-compose -f docker-compose.dev.yml up -d --build operations-api